package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Clinic;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ClinicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLINIC
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    Clinic getClinic(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLINIC
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int insert(Clinic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLINIC
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    Clinic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLINIC
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    List<Clinic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLINIC
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int updateByPrimaryKey(Clinic record);
}