package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Doctor;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    public List<Doctor> getDoctors();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    Doctor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int updateByPrimaryKey(Doctor record);
}