package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Patient;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    Patient selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    int updateByPrimaryKey(Patient record);
}