package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Clinic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLINIC.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    private Long id;

    private List<Doctor> doctors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLINIC.TITLE
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLINIC.ID
     *
     * @return the value of PUBLIC.CLINIC.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLINIC.ID
     *
     * @param id the value for PUBLIC.CLINIC.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLINIC.TITLE
     *
     * @return the value of PUBLIC.CLINIC.TITLE
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLINIC.TITLE
     *
     * @param title the value for PUBLIC.CLINIC.TITLE
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}