package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.CLINIC_ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    private Integer clinicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.ID
     *
     * @return the value of PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.ID
     *
     * @param id the value for PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @return the value of PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @param name the value for PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.CLINIC_ID
     *
     * @return the value of PUBLIC.DOCTOR.CLINIC_ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public Integer getClinicId() {
        return clinicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.CLINIC_ID
     *
     * @param clinicId the value for PUBLIC.DOCTOR.CLINIC_ID
     *
     * @mbg.generated Wed May 25 10:42:55 EEST 2022
     */
    public void setClinicId(Integer clinicId) {
        this.clinicId = clinicId;
    }
}